version: '3.9'
services:
  iventoy:
    build:
      context: .
      args:
        VERSION: 1.0.18
    container_name: iventoy
    restart: unless-stopped
    privileged: true #must be true
    ports:
      - 16000:16000
      - 26000:26000
    volumes:
      - /ISO_PATH:/iventoy/iso
      - ./data:/iventoy/data
