version: '3.9'
services:
  iventoy:
    build: .
    container_name: iventoy
    restart: unless-stopped
    privileged: true #must be true
    args:
        IVENTOY: 1.0.18
    ports:
      - 16000:16000
      - 26000:26000
    volumes:
      - /ISO_PATH:/iso
      - ./data:/data
